### ISSUE TITLE
Semver git tag for bower

### ISSUE THREAD

**Issue by simonexmachina** [achesco/browser-nano#1]
Bower uses Git tags for versioning. Can you please tag this repo with the current version? You can use `bower version` to do this.

**Comment by achesco** [comment]
Sorry, as far as I can see bower.json contains current version already. So
`bower version 6.1.4-alpha`
gives me
`Version not changed` message

**Comment by simonexmachina** [comment]
Right, that's bower being a bit unhelpful there. In that case you just need to create the Git tag manually:

```
git tag v6.1.4-alpha
git push --tags
```

You can use `bower version` in the future and it should do what it says: update the `bower.json` and create the Git tag.

**Comment by achesco** [comment]
done
